"""remove isadmin firld from user table

Revision ID: 0234322302ee
Revises: 8970c540f46d
Create Date: 2022-01-25 14:33:35.293075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0234322302ee'
down_revision = '8970c540f46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isAdmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
