"""remove the field in email token

Revision ID: 0ef8c38b788b
Revises: 88654ad6c914
Create Date: 2022-01-25 04:32:25.172003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef8c38b788b'
down_revision = '88654ad6c914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
