"""create super admin table ,28 jan

Revision ID: 15d4072bef48
Revises: cdad778471f5
Create Date: 2022-01-24 23:18:10.087323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d4072bef48'
down_revision = 'cdad778471f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admin_address'), 'super_admin', ['address'], unique=False)
    op.create_index(op.f('ix_super_admin_email'), 'super_admin', ['email'], unique=True)
    op.create_index(op.f('ix_super_admin_id'), 'super_admin', ['id'], unique=False)
    op.create_index(op.f('ix_super_admin_name'), 'super_admin', ['name'], unique=False)
    op.create_index(op.f('ix_super_admin_password'), 'super_admin', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_super_admin_password'), table_name='super_admin')
    op.drop_index(op.f('ix_super_admin_name'), table_name='super_admin')
    op.drop_index(op.f('ix_super_admin_id'), table_name='super_admin')
    op.drop_index(op.f('ix_super_admin_email'), table_name='super_admin')
    op.drop_index(op.f('ix_super_admin_address'), table_name='super_admin')
    op.drop_table('super_admin')
    # ### end Alembic commands ###
