"""remove date field from email_token table

Revision ID: 18be38df7824
Revises: 0ef8c38b788b
Create Date: 2022-01-25 06:37:27.859672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18be38df7824'
down_revision = '0ef8c38b788b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_token', 'expired_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_token', sa.Column('expired_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
