"""Add date field from email_token table

Revision ID: 27cf99d67021
Revises: 18be38df7824
Create Date: 2022-01-25 06:38:31.013439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cf99d67021'
down_revision = '18be38df7824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_token', sa.Column('expired_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_token', 'expired_in')
    # ### end Alembic commands ###
