"""Added image field from product table

Revision ID: 358aa06f0d4e
Revises: 6c97b304b2c2
Create Date: 2022-02-15 12:44:46.983918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358aa06f0d4e'
down_revision = '6c97b304b2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###
