"""Remove user_id field from permission table

Revision ID: 48d365fa0e84
Revises: ea066c775fc6
Create Date: 2022-01-25 20:12:41.903001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d365fa0e84'
down_revision = 'ea066c775fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_user_id_fkey', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('permissions_user_id_fkey', 'permissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
