"""delete role_id field from user table

Revision ID: 68bfe9623939
Revises: c166b7aaff1c
Create Date: 2022-01-26 07:32:33.672930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bfe9623939'
down_revision = 'c166b7aaff1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_users_role_id', 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###
