"""delete image field from product table

Revision ID: 6c97b304b2c2
Revises: cb73a3994363
Create Date: 2022-02-15 12:21:42.778314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c97b304b2c2'
down_revision = 'cb73a3994363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
