"""manipulate field in permission tables ,27 jan

Revision ID: 7065aa1dff80
Revises: ebbfd33ee937
Create Date: 2022-01-24 19:53:54.301102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7065aa1dff80'
down_revision = 'ebbfd33ee937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_user_id_fkey', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('permissions_user_id_fkey', 'permissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
