"""delete image field from product table

Revision ID: 7eaa8d539284
Revises: 358aa06f0d4e
Create Date: 2022-02-16 03:55:01.525187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eaa8d539284'
down_revision = '358aa06f0d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
