"""remone status field

Revision ID: 80765bb838ac
Revises: 27cf99d67021
Create Date: 2022-01-25 06:57:34.765743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80765bb838ac'
down_revision = '27cf99d67021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_token', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_token', sa.Column('status', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
