"""set datetime ,28 jan

Revision ID: 88654ad6c914
Revises: d4199050541d
Create Date: 2022-01-25 04:29:52.709201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88654ad6c914'
down_revision = 'd4199050541d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
