"""Add status field

Revision ID: 8970c540f46d
Revises: 80765bb838ac
Create Date: 2022-01-25 06:58:42.962411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8970c540f46d'
down_revision = '80765bb838ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_token', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_token', 'status')
    # ### end Alembic commands ###
