"""default time set ,28 jan

Revision ID: d4199050541d
Revises: e532913c1ec6
Create Date: 2022-01-25 04:21:53.366784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4199050541d'
down_revision = 'e532913c1ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
