"""Added emailtoken table in field sequence ,28 jan

Revision ID: da9ef1a17d52
Revises: 11637492978b
Create Date: 2022-01-25 04:07:53.644699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9ef1a17d52'
down_revision = '11637492978b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_token_id', table_name='email_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_email_token_id', 'email_token', ['id'], unique=False)
    # ### end Alembic commands ###
