"""remove role_id field from user table

Revision ID: de9cded11891
Revises: c130297662b2
Create Date: 2022-01-26 23:56:32.682966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9cded11891'
down_revision = 'c130297662b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_users_role_id', 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###
