"""Added user_id field from permission table

Revision ID: ea066c775fc6
Revises: faed6aa4d167
Create Date: 2022-01-25 19:23:21.683228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea066c775fc6'
down_revision = 'faed6aa4d167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'user_id')
    # ### end Alembic commands ###
