"""update field role_name to role_id from user_role table

Revision ID: f83587933016
Revises: dd7e3b31e677
Create Date: 2022-01-25 15:17:21.353539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83587933016'
down_revision = 'dd7e3b31e677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_index('ix_user_role_role_name', table_name='user_role')
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.drop_column('user_role', 'role_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.create_index('ix_user_role_role_name', 'user_role', ['role_name'], unique=False)
    op.drop_column('user_role', 'role_id')
    # ### end Alembic commands ###
