# Generated by Django 3.2.10 on 2022-03-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarSeller',
        ),
    ]
