# Generated by Django 3.2.10 on 2022-03-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_seller', '0003_carseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carseller',
            name='picture',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
